
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cesar31.activaciones.parser;

/** CUP generated class containing symbol constants. */
public class ActivacionesParserSym {
  /* terminals */
  public static final int TIMES = 15;
  public static final int PLUS = 13;
  public static final int INT = 18;
  public static final int RPAREN = 8;
  public static final int EQUAL = 12;
  public static final int SEMI = 25;
  public static final int CHAR = 19;
  public static final int END = 10;
  public static final int ERROR = 17;
  public static final int LPAREN = 7;
  public static final int COLON = 11;
  public static final int ID = 3;
  public static final int PROGRAM = 4;
  public static final int BEGIN = 9;
  public static final int BOOLEAN = 21;
  public static final int STRING = 22;
  public static final int COMMA = 26;
  public static final int EOF = 0;
  public static final int DIVIDE = 16;
  public static final int PROCESS = 5;
  public static final int MINUS = 14;
  public static final int error = 1;
  public static final int BOOL = 23;
  public static final int INTEGER = 2;
  public static final int REAL = 20;
  public static final int VAR = 6;
  public static final int UMINUS = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "ID",
  "PROGRAM",
  "PROCESS",
  "VAR",
  "LPAREN",
  "RPAREN",
  "BEGIN",
  "END",
  "COLON",
  "EQUAL",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "ERROR",
  "INT",
  "CHAR",
  "REAL",
  "BOOLEAN",
  "STRING",
  "BOOL",
  "UMINUS",
  "SEMI",
  "COMMA"
  };
}

